blank_issues_enabled: false
contact_links:
  - name: Infrastructure-Workflow Issues
    url: /path/to/infrastructure-workflow/templates
    about: "Create issues related to infrastructure and workflow"