blank_issues_enabled: false
contact_links:
  - name: Infrastructure-Workflow Issues
    url: "https://github.com/solecms/soleink/tree/main/.github/ISSUE_TEMPLATE/infrastructure-workflow"
    about: "Create issues related to infrastructure and workflow"