blank_issues_enabled: false
contact_links:
  - name: Infrastructure-Workflow Issues
    url: https://github.com/solecms/soleink/issues/new?template=infrastructure-workflow
    about: Enhancements and issues related to project structure, workflow optimization, and documentation.
