name: Move PR to Review

on:
  pull_request:
    types: [opened]

jobs:
  move-card:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get Token
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@v3
      with:
        application_id: ${{ vars.APP_ID }}
        application_private_key: ${{ secrets.APP_SECRET }}

    - name: Move PR to Review
      uses: actions/github-script@v7
      with:
        github-token: ${{ steps.get_workflow_token.outputs.token }}
        script: |
          const projectOwner = 'solecms';
          const projectNumber = 3; // Your project number
          const columnName = 'Review/QA';

          // Get the organization projects
          const { organization } = await github.graphql(`
            query($owner: String!) {
              organization(login: $owner) {
                projectsV2(first: 100) {
                  nodes {
                    id
                    number
                    title
                    fields(first: 100) {
                      nodes {
                        __typename
                        ... on ProjectV2FieldCommon {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }
          `, {
            owner: projectOwner
          });

          if (!organization) {
            throw new Error(`Organization '${projectOwner}' not found`);
          }

          const projects = organization.projectsV2.nodes ?? [];
          console.log("Projects Response:", projects);

          // Find the project by number
          const project = projects.find(proj => proj.number === projectNumber);
          if (!project) {
            throw new Error(`Project number '${projectNumber}' not found for owner '${projectOwner}'`);
          }

          const projectId = project.id;
          console.log(`Found project ID: ${projectId}`);

          // Get the field ID
          const fields = project.fields.nodes;
          const column = fields.find(field => field.name === columnName);
          if (!column) {
            throw new Error(`Column '${columnName}' not found in project '${projectNumber}'`);
          }

          const columnId = column.id;

          // Get the PR ID
          const prId = context.payload.pull_request.node_id;

          // Add the PR to the project column
          await github.graphql(`
            mutation($projectId: ID!, $contentId: ID!, $fieldId: ID!) {
              addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId, fieldId: $fieldId}) {
                item {
                  id
                }
              }
            }
          `, {
            projectId: projectId,
            contentId: prId,
            fieldId: columnId
          });

          console.log(`Successfully added PR ${prId} to project column ${columnName}`);
