name: Move PR to Review

on:
  pull_request:
    types: [opened]

jobs:
  move-card:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get Token
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@v3
      with:
        application_id: ${{ vars.APP_ID }}
        application_private_key: ${{ secrets.APP_SECRET }}

    - name: Move PR to Review
      uses: actions/github-script@v7
      with:
        github-token: ${{ steps.get_workflow_token.outputs.token }}
        script: |
          const updateProjectStatus = require('./src/lib/workflow/update-project-status');
          updateProjectStatus(github, context);
          

